services:
  db:
    image: postgres:16
    container_name: coupon-db
    restart: always
    environment:
      POSTGRES_DB: coupon
      POSTGRES_USER: coupon_user
      POSTGRES_PASSWORD: coupon_pass
      TZ: Asia/Kolkata
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: coupon-app
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coupon
      SPRING_DATASOURCE_USERNAME: coupon_user
      SPRING_DATASOURCE_PASSWORD: coupon_pass

volumes:
  db_data:
