services:
  db:
    image: postgres:16
    container_name: coupon-db
    environment:
      POSTGRES_DB: coupondb
      POSTGRES_USER: coupon_user
      POSTGRES_PASSWORD: coupon_pass
      TZ: Asia/Kolkata
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: coupon-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://coupon-db:5432/coupon
      SPRING_DATASOURCE_USERNAME: coupon_user
      SPRING_DATASOURCE_PASSWORD: coupon_pass

volumes:
  db_data:
