spring.application.name=coupon-engine
server.servlet.context-path=/rule-engine/api
server.address=0.0.0.0

# Swagger Documentation
springdoc.api-docs.path=/api-docs

# PostgreSQL database connection properties
spring.datasource.url=jdbc:postgresql://db:5432/coupon
spring.datasource.username=coupon_user
spring.datasource.password=coupon_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
